version: '3.7'
services:
  postgres:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: myschedule
    ports:
    - '5432:5432'
    volumes:
    - postgres:/var/lib/posgresql/data 
    container_name: postgres
volumes:
  postgres:
    external: true